package greendao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import greendao.SleepSessionPoint;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table SLEEP_SESSION_POINT.
*/
public class SleepSessionPointDao extends AbstractDao<SleepSessionPoint, Long> {

    public static final String TABLENAME = "SLEEP_SESSION_POINT";

    /**
     * Properties of entity SleepSessionPoint.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Type = new Property(1, int.class, "type", false, "TYPE");
        public final static Property Value = new Property(2, int.class, "value", false, "VALUE");
        public final static Property ParentId = new Property(3, Long.class, "parentId", false, "PARENT_ID");
    };

    private DaoSession daoSession;

    private Query<SleepSessionPoint> sleepSession_ChildsSleepSessionPointQuery;

    public SleepSessionPointDao(DaoConfig config) {
        super(config);
    }
    
    public SleepSessionPointDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'SLEEP_SESSION_POINT' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'TYPE' INTEGER NOT NULL ," + // 1: type
                "'VALUE' INTEGER NOT NULL ," + // 2: value
                "'PARENT_ID' INTEGER);"); // 3: parentId
        // Add Indexes
        db.execSQL("CREATE INDEX " + constraint + "IDX_SLEEP_SESSION_POINT_TYPE ON SLEEP_SESSION_POINT" +
                " (TYPE);");
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'SLEEP_SESSION_POINT'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, SleepSessionPoint entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getType());
        stmt.bindLong(3, entity.getValue());
 
        Long parentId = entity.getParentId();
        if (parentId != null) {
            stmt.bindLong(4, parentId);
        }
    }

    @Override
    protected void attachEntity(SleepSessionPoint entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public SleepSessionPoint readEntity(Cursor cursor, int offset) {
        SleepSessionPoint entity = new SleepSessionPoint( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getInt(offset + 1), // type
            cursor.getInt(offset + 2), // value
            cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3) // parentId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, SleepSessionPoint entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setType(cursor.getInt(offset + 1));
        entity.setValue(cursor.getInt(offset + 2));
        entity.setParentId(cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(SleepSessionPoint entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(SleepSessionPoint entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "childsSleepSessionPoint" to-many relationship of SleepSession. */
    public List<SleepSessionPoint> _querySleepSession_ChildsSleepSessionPoint(Long parentId) {
        synchronized (this) {
            if (sleepSession_ChildsSleepSessionPointQuery == null) {
                QueryBuilder<SleepSessionPoint> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.ParentId.eq(null));
                sleepSession_ChildsSleepSessionPointQuery = queryBuilder.build();
            }
        }
        Query<SleepSessionPoint> query = sleepSession_ChildsSleepSessionPointQuery.forCurrentThread();
        query.setParameter(0, parentId);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getSleepSessionDao().getAllColumns());
            builder.append(" FROM SLEEP_SESSION_POINT T");
            builder.append(" LEFT JOIN SLEEP_SESSION T0 ON T.'PARENT_ID'=T0.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected SleepSessionPoint loadCurrentDeep(Cursor cursor, boolean lock) {
        SleepSessionPoint entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        SleepSession sleepSession = loadCurrentOther(daoSession.getSleepSessionDao(), cursor, offset);
        entity.setSleepSession(sleepSession);

        return entity;    
    }

    public SleepSessionPoint loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<SleepSessionPoint> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<SleepSessionPoint> list = new ArrayList<SleepSessionPoint>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<SleepSessionPoint> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<SleepSessionPoint> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
